blank_issues_enabled: false
contact_links:
  - name: 对 PanelX 项目有其他问题
    url: https://www.panelx.cn
    about: 如果想要进一步了解 PanelX 项目，欢迎发送邮件到 support@panelx.cn 进行提问。
  - name: 反馈安全问题 (Report Security Bug)
    url: mailto://support@panelx.cn
    about: 请通过邮箱 support@panelx.cn 反馈安全问题 (Please report security vulnerabilities to support@panelx.cn)