system:
  db_file: panelx.db
  base_dir: /opt
  mode: dev
  repo_url: https://resource.panelx.cn/package
<<<<<<< HEAD
  app_repo: https://apps-assets.fit2cloud.com
=======
  app_repo: https://assets.panelx.com
>>>>>>> daff865b
  is_demo: false
  port: 9999
  username: admin
  password: admin123

log:
  level: debug
  time_zone: Asia/Shanghai
  log_name: panelx
  log_suffix: .log
  max_backup: 10
